### ISSUE TITLE
加载模型出错，ValueError: Unrecognized configuration class <class 'transformers_modules.fuzi-mingcha-v1_0.configuration_chatglm.ChatGLMConfig'>

### ISSUE THREAD

**Issue by zyh3826** [irlab-sdu/fuzi.mingcha#13]
您好按照你的方式加载模型出错，@Furyton @zwh-sdu  错误如下：
```shell
>>> model = AutoModelForCausalLM.from_pretrained(p, trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/zhaoyuhang/anaconda3/envs/fuzimingcha/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.fuzi-mingcha-v1_0.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

```

**Comment by zyh3826** [comment]
还有个就是`pylucene`的`api.py`里有一系列`org.apache.lucene`，请问这个是咋安装的，因为我的`singularity`安装后没法运行，得自己安装包

**Comment by Furyton** [comment]
> 您好按照你的方式加载模型出错，@Furyton @zwh-sdu 错误如下：
> 
> ```shell
> >>> model = AutoModelForCausalLM.from_pretrained(p, trust_remote_code=True)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/zhaoyuhang/anaconda3/envs/fuzimingcha/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
>     raise ValueError(
> ValueError: Unrecognized configuration class <class 'transformers_modules.fuzi-mingcha-v1_0.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
> Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
> ```

您好，感谢您的关注。
这里需要使用 `AutoModel` 来加载模型，即
```python
from transformers import AutoModel
model = AutoModel.from_pretrained("/path/to/fuzi-mingcha-v1_0", trust_remote_code=True)
```

**Comment by zyh3826** [comment]
> > 您好按照你的方式加载模型出错，@Furyton @zwh-sdu 错误如下：
> > ```shell
> > >>> model = AutoModelForCausalLM.from_pretrained(p, trust_remote_code=True)
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "/data/zhaoyuhang/anaconda3/envs/fuzimingcha/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
> >     raise ValueError(
> > ValueError: Unrecognized configuration class <class 'transformers_modules.fuzi-mingcha-v1_0.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
> > Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
> > ```
> 
> 您好，感谢您的关注。 这里需要使用 `AutoModel` 来加载模型，即
> 
> ```python
> from transformers import AutoModel
> model = AutoModel.from_pretrained("/path/to/fuzi-mingcha-v1_0", trust_remote_code=True)
> ```

谢谢回复，没注意，习惯用`AutoModelForCausalLM`了
还有就是`pylucene_task*`的api.py里有一系列org.apache.lucene，请问这个是咋安装的呢

**Comment by Furyton** [comment]
您好，目前我们使用的 `lucene` 的安装方式确实有些繁琐，我们会在近期采用一版新的检索方案，简化安装过程，更新后会告知您

感谢您的关注和理解。

**Comment by xinghen91** [comment]
![image](https://github.com/irlab-sdu/fuzi.mingcha/assets/4225559/dd669d75-6e0c-420c-98a3-4247be773e11)
![image](https://github.com/irlab-sdu/fuzi.mingcha/assets/4225559/f1068add-2ebf-4860-a5c5-cc833aa6d19e)
我整体把项目搭建起来了，通过镜像跑起来之后，用浏览器访问地址报这个错，不知道是访问地址不对还是部署哪里有问题，能帮忙解答下么，或者有没有社群能够讨论？

**Comment by zwh-sdu** [comment]
> ![image](https://private-user-images.githubusercontent.com/4225559/299515940-dd669d75-6e0c-420c-98a3-4247be773e11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzQzNTQsIm5iZiI6MTcwNjE3NDA1NCwicGF0aCI6Ii80MjI1NTU5LzI5OTUxNTk0MC1kZDY2OWQ3NS02ZTBjLTQyMGMtOThhMy00MjQ3YmU3NzNlMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDkxNDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVlMDI0NGFlYjhjZTI1MTVlMjhjNzIxYjhjYWQzNDZmNTBmMDgzMzk5M2IyNmY5NDE3MWIxMmM0ZDk3MmFmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U_HDdEgD8O0-Dv_rnk31Nx38Y-5TsicxCLsB6APDd1o) ![image](https://private-user-images.githubusercontent.com/4225559/299516018-f1068add-2ebf-4860-a5c5-cc833aa6d19e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzQzNTQsIm5iZiI6MTcwNjE3NDA1NCwicGF0aCI6Ii80MjI1NTU5LzI5OTUxNjAxOC1mMTA2OGFkZC0yZWJmLTQ4NjAtYTVjNS1jYzgzM2FhNmQxOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDkxNDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM3N2FjN2ZiMWU0ODJiNGVkNzgyYTc0Mzk0NzMxMzVlYWNjOTdiNGM5MDBjMTVkYzU5MGJjMjNjNDVjOWY0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8YyIRCcDSXHmAPgsD7Erku2ANwPDhUnDc0Mc3l6NiP8) 我整体把项目搭建起来了，通过镜像跑起来之后，用浏览器访问地址报这个错，不知道是访问地址不对还是部署哪里有问题，能帮忙解答下么，或者有没有社群能够讨论？

您好，这一步部署的只是检索模块，您部署出来的这个地址是在 cli_demo.py 中检索部分请求的地址
即下面这行命令中的 "法条检索对应部署的 pylucene 地址" 和 "类案检索对应部署的 pylucene 地址"
```shell
python cli_demo.py --url_lucene_task1 "法条检索对应部署的 pylucene 地址"  --url_lucene_task2 "类案检索对应部署的 pylucene 地址"
```

**Comment by zwh-sdu** [comment]
> > > 您好按照你的方式加载模型出错，@Furyton @zwh-sdu 错误如下：
> > > ```shell
> > > >>> model = AutoModelForCausalLM.from_pretrained(p, trust_remote_code=True)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/data/zhaoyuhang/anaconda3/envs/fuzimingcha/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
> > >     raise ValueError(
> > > ValueError: Unrecognized configuration class <class 'transformers_modules.fuzi-mingcha-v1_0.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
> > > Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
> > > ```
> > 
> > 
> > 您好，感谢您的关注。 这里需要使用 `AutoModel` 来加载模型，即
> > ```python
> > from transformers import AutoModel
> > model = AutoModel.from_pretrained("/path/to/fuzi-mingcha-v1_0", trust_remote_code=True)
> > ```
> 
> 谢谢回复，没注意，习惯用`AutoModelForCausalLM`了 还有就是`pylucene_task*`的api.py里有一系列org.apache.lucene，请问这个是咋安装的呢

您好，我们更新了 ES 检索的部署代码，您可以尝试用 ES 替代 pylucene 进行部署

**Comment by chloroplast567** [comment]
请问您更推荐哪种检索方式呢？PyLucene方式部署起来感觉有些繁琐
